{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyM0c5VaiQpRDIlV5+YL2BuI",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "ir",
      "display_name": "R"
    },
    "language_info": {
      "name": "R"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Kavin-2005/mini-project-in-R/blob/main/weather.R\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# ===== AIR QUALITY REPORT, ANALYSIS & FORECASTING =====\n",
        "\n",
        "# Step 1: Install packages (run once)\n",
        "install.packages(c(\"tidyverse\", \"lubridate\", \"forecast\", \"tseries\"))\n",
        "\n",
        "# Step 2: Load libraries\n",
        "library(tidyverse)\n",
        "library(lubridate)\n",
        "library(forecast)\n",
        "library(tseries)\n",
        "\n",
        "# Step 3: Upload CSV (in RStudio or Colab-like R env, choose file)\n",
        "file_name <- file.choose()\n",
        "\n",
        "# Step 4: Read file\n",
        "df <- read.csv(file_name, fileEncoding = \"latin1\", stringsAsFactors = FALSE)\n",
        "\n",
        "# Step 5: Clean & prepare data\n",
        "if (\"date\" %in% names(df)) {\n",
        "  df$date <- as.Date(df$date, format = \"%Y-%m-%d\")\n",
        "}\n",
        "\n",
        "pollutant_cols <- c(\"so2\", \"no2\", \"rspm\", \"spm\", \"pm2_5\")\n",
        "\n",
        "# Remove rows with all pollutant columns missing\n",
        "df <- df %>%\n",
        "  filter(rowSums(is.na(select(., all_of(pollutant_cols)))) < length(pollutant_cols))\n",
        "\n",
        "# Step 6: Summary table - Average pollutants per state\n",
        "avg_pollutants <- df %>%\n",
        "  group_by(state) %>%\n",
        "  summarise(across(all_of(pollutant_cols), mean, na.rm = TRUE)) %>%\n",
        "  arrange(desc(pm2_5))\n",
        "\n",
        "cat(\"📊 Average Pollutant Levels by State:\\n\")\n",
        "print(avg_pollutants)\n",
        "\n",
        "# Step 7: Bar Chart - Average PM2.5 per state\n",
        "ggplot(avg_pollutants, aes(x = pm2_5, y = reorder(state, pm2_5))) +\n",
        "  geom_col(fill = \"darkgreen\") +\n",
        "  labs(title = \"Average PM2.5 Levels by State\",\n",
        "       x = \"PM2.5 (µg/m³)\",\n",
        "       y = \"State\") +\n",
        "  theme_minimal()\n",
        "\n",
        "# Step 8: Time Series Plot - PM2.5\n",
        "if (\"pm2_5\" %in% names(df) && \"date\" %in% names(df)) {\n",
        "  ggplot(df, aes(x = date, y = pm2_5)) +\n",
        "    geom_line(color = \"red\") +\n",
        "    labs(title = \"PM2.5 Levels Over Time\",\n",
        "         x = \"Date\",\n",
        "         y = \"PM2.5 (µg/m³)\") +\n",
        "    theme_minimal()\n",
        "}\n",
        "\n",
        "# Step 9: Correlation Plot - SO2 vs NO2\n",
        "if (\"so2\" %in% names(df) && \"no2\" %in% names(df)) {\n",
        "  ggplot(df, aes(x = so2, y = no2)) +\n",
        "    geom_point(color = \"purple\", alpha = 0.6) +\n",
        "    geom_smooth(method = \"lm\", color = \"black\") +\n",
        "    labs(title = \"Correlation: SO₂ vs NO₂\",\n",
        "         x = \"SO₂ (µg/m³)\",\n",
        "         y = \"NO₂ (µg/m³)\") +\n",
        "    theme_minimal()\n",
        "}\n",
        "\n",
        "# Step 10: PM2.5 Forecasting\n",
        "if (\"pm2_5\" %in% names(df) && \"date\" %in% names(df)) {\n",
        "  ts_data <- df %>%\n",
        "    filter(!is.na(pm2_5)) %>%\n",
        "    arrange(date) %>%\n",
        "    mutate(month = floor_date(date, \"month\")) %>%\n",
        "    group_by(month) %>%\n",
        "    summarise(pm2_5 = mean(pm2_5, na.rm = TRUE))\n",
        "\n",
        "  # Convert to time series object\n",
        "  pm_ts <- ts(ts_data$pm2_5, start = c(year(min(ts_data$month)), month(min(ts_data$month))), frequency = 12)\n",
        "\n",
        "  # Fit ARIMA model\n",
        "  fit <- auto.arima(pm_ts, seasonal = TRUE)\n",
        "\n",
        "  # Forecast next 12 months\n",
        "  fc <- forecast(fit, h = 12)\n",
        "\n",
        "  # Plot forecast\n",
        "  autoplot(fc) +\n",
        "    labs(title = \"Forecast of PM2.5 Levels for Next 12 Months\",\n",
        "         x = \"Date\",\n",
        "         y = \"PM2.5 (µg/m³)\") +\n",
        "    theme_minimal()\n",
        "}"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ExZ6kGrPM1oL",
        "outputId": "089badc8-f0da-4bdb-c7cc-ba944b88b1f5"
      },
      "execution_count": null,
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "Installing packages into ‘/usr/local/lib/R/site-library’\n",
            "(as ‘lib’ is unspecified)\n",
            "\n",
            "also installing the dependencies ‘xts’, ‘TTR’, ‘colorspace’, ‘fracdiff’, ‘lmtest’, ‘timeDate’, ‘urca’, ‘zoo’, ‘RcppArmadillo’, ‘quadprog’, ‘quantmod’\n",
            "\n",
            "\n",
            "── \u001b[1mAttaching core tidyverse packages\u001b[22m ──────────────────────── tidyverse 2.0.0 ──\n",
            "\u001b[32m✔\u001b[39m \u001b[34mdplyr    \u001b[39m 1.1.4     \u001b[32m✔\u001b[39m \u001b[34mreadr    \u001b[39m 2.1.5\n",
            "\u001b[32m✔\u001b[39m \u001b[34mforcats  \u001b[39m 1.0.0     \u001b[32m✔\u001b[39m \u001b[34mstringr  \u001b[39m 1.5.1\n",
            "\u001b[32m✔\u001b[39m \u001b[34mggplot2  \u001b[39m 3.5.2     \u001b[32m✔\u001b[39m \u001b[34mtibble   \u001b[39m 3.3.0\n",
            "\u001b[32m✔\u001b[39m \u001b[34mlubridate\u001b[39m 1.9.4     \u001b[32m✔\u001b[39m \u001b[34mtidyr    \u001b[39m 1.3.1\n",
            "\u001b[32m✔\u001b[39m \u001b[34mpurrr    \u001b[39m 1.1.0     \n",
            "── \u001b[1mConflicts\u001b[22m ────────────────────────────────────────── tidyverse_conflicts() ──\n",
            "\u001b[31m✖\u001b[39m \u001b[34mdplyr\u001b[39m::\u001b[32mfilter()\u001b[39m masks \u001b[34mstats\u001b[39m::filter()\n",
            "\u001b[31m✖\u001b[39m \u001b[34mdplyr\u001b[39m::\u001b[32mlag()\u001b[39m    masks \u001b[34mstats\u001b[39m::lag()\n",
            "\u001b[36mℹ\u001b[39m Use the conflicted package (\u001b[3m\u001b[34m<http://conflicted.r-lib.org/>\u001b[39m\u001b[23m) to force all conflicts to become errors\n",
            "Registered S3 method overwritten by 'quantmod':\n",
            "  method            from\n",
            "  as.zoo.data.frame zoo \n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Step 2: Load libraries\n",
        "library(tidyverse)\n",
        "library(lubridate)\n",
        "library(forecast)\n",
        "library(tseries)\n",
        "\n",
        "# Step 3: Upload CSV (in RStudio or Colab-like R env, choose file)\n",
        "file_name <- file.choose()\n",
        "\n",
        "# Step 4: Read file\n",
        "df <- read.csv(file_name, fileEncoding = \"latin1\", stringsAsFactors = FALSE)\n",
        "\n",
        "# Step 5: Clean & prepare data\n",
        "if (\"date\" %in% names(df)) {\n",
        "  df$date <- as.Date(df$date, format = \"%Y-%m-%d\")\n",
        "}\n",
        "\n",
        "pollutant_cols <- c(\"so2\", \"no2\", \"rspm\", \"spm\", \"pm2_5\")\n",
        "\n",
        "# Remove rows with all pollutant columns missing\n",
        "df <- df %>%\n",
        "  filter(rowSums(is.na(select(., all_of(pollutant_cols)))) < length(pollutant_cols))\n",
        "\n",
        "# Step 6: Summary table - Average pollutants per state\n",
        "avg_pollutants <- df %>%\n",
        "  group_by(state) %>%\n",
        "  summarise(across(all_of(pollutant_cols), mean, na.rm = TRUE)) %>%\n",
        "  arrange(desc(pm2_5))\n",
        "\n",
        "cat(\"📊 Average Pollutant Levels by State:\\n\")\n",
        "print(avg_pollutants)\n",
        "\n",
        "# Step 7: Bar Chart - Average PM2.5 per state\n",
        "ggplot(avg_pollutants, aes(x = pm2_5, y = reorder(state, pm2_5))) +\n",
        "  geom_col(fill = \"darkgreen\") +\n",
        "  labs(title = \"Average PM2.5 Levels by State\",\n",
        "       x = \"PM2.5 (µg/m³)\",\n",
        "       y = \"State\") +\n",
        "  theme_minimal()\n",
        "\n",
        "# Step 8: Time Series Plot - PM2.5\n",
        "if (\"pm2_5\" %in% names(df) && \"date\" %in% names(df)) {\n",
        "  ggplot(df, aes(x = date, y = pm2_5)) +\n",
        "    geom_line(color = \"red\") +\n",
        "    labs(title = \"PM2.5 Levels Over Time\",\n",
        "         x = \"Date\",\n",
        "         y = \"PM2.5 (µg/m³)\") +\n",
        "    theme_minimal()\n",
        "}\n",
        "\n",
        "# Step 9: Correlation Plot - SO2 vs NO2\n",
        "if (\"so2\" %in% names(df) && \"no2\" %in% names(df)) {\n",
        "  ggplot(df, aes(x = so2, y = no2)) +\n",
        "    geom_point(color = \"purple\", alpha = 0.6) +\n",
        "    geom_smooth(method = \"lm\", color = \"black\") +\n",
        "    labs(title = \"Correlation: SO₂ vs NO₂\",\n",
        "         x = \"SO₂ (µg/m³)\",\n",
        "         y = \"NO₂ (µg/m³)\") +\n",
        "    theme_minimal()\n",
        "}\n",
        "\n",
        "# Step 10: PM2.5 Forecasting\n",
        "if (\"pm2_5\" %in% names(df) && \"date\" %in% names(df)) {\n",
        "  ts_data <- df %>%\n",
        "    filter(!is.na(pm2_5)) %>%\n",
        "    arrange(date) %>%\n",
        "    mutate(month = floor_date(date, \"month\")) %>%\n",
        "    group_by(month) %>%\n",
        "    summarise(pm2_5 = mean(pm2_5, na.rm = TRUE))\n",
        "\n",
        "  # Convert to time series object\n",
        "  pm_ts <- ts(ts_data$pm2_5, start = c(year(min(ts_data$month)), month(min(ts_data$month))), frequency = 12)\n",
        "\n",
        "  # Fit ARIMA model\n",
        "  fit <- auto.arima(pm_ts, seasonal = TRUE)\n",
        "\n",
        "  # Forecast next 12 months\n",
        "  fc <- forecast(fit, h = 12)\n",
        "\n",
        "  # Plot forecast\n",
        "  autoplot(fc) +\n",
        "    labs(title = \"Forecast of PM2.5 Levels for Next 12 Months\",\n",
        "         x = \"Date\",\n",
        "         y = \"PM2.5 (µg/m³)\") +\n",
        "    theme_minimal()\n",
        "}"
      ],
      "metadata": {
        "id": "h-xjLGpgNr0C"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}